### PR TITLE
[SPE-1074] Support java publishing

### PR DESCRIPTION
**Pull request by chase-crumbaugh**
Adds support for java publishing. Tested as a standalone job, has not been tested as part of the full workflow

### CODE REVIEW

**Comment by chase-crumbaugh** [comment]
@TristanSpeakEasy I'm unsure of the best way to test this. I got it working originally by just having the publish action as a standalone thing in a test repo. I got it working there, but not sure how to test as part of the full generation flow

**Comment by TristanSpeakEasy** [comment]
> @TristanSpeakEasy I'm unsure of the best way to test this. I got it working originally by just having the publish action as a standalone thing in a test repo. I got it working there, but not sure how to test as part of the full generation flow

so yeah testing of this prior to getting it merged isn't really possible (at least I haven't figured out how yet), so we just need to get it in, set it up on our own https://github.com/speakeasy-api/speakeasy-client-sdk-java repo and iterate until it works.

**Review by TristanSpeakEasy — CHANGES_REQUESTED** [review]
So there are some missing changes here to update the releases.md with the publish java package information.

I will actually have a PR up myself soon showing the work required for PHP publishing that you can use as a template for updating this

**Comment by TristanSpeakEasy** [comment]
> So there are some missing changes here to update the releases.md with the publish java package information.
> 
> I will actually have a PR up myself soon showing the work required for PHP publishing that you can use as a template for updating this

Here is the PR https://github.com/speakeasy-api/sdk-generation-action/pull/8 I am going to get this in, tested and released which should answer all the questions of what you need to do to complete this PR

**Comment by TristanSpeakEasy** [comment]
> > @TristanSpeakEasy I'm unsure of the best way to test this. I got it working originally by just having the publish action as a standalone thing in a test repo. I got it working there, but not sure how to test as part of the full generation flow
> 
> so yeah testing of this prior to getting it merged isn't really possible (at least I haven't figured out how yet), so we just need to get it in, set it up on our own https://github.com/speakeasy-api/speakeasy-client-sdk-java repo and iterate until it works.

okay after going through some iteration myself we possibly don't need to republish the package each time we make a change as you can link to a git commit sha from workflows. I will try this out and report back on its success

**Comment by TristanSpeakEasy** [comment]
> > > @TristanSpeakEasy I'm unsure of the best way to test this. I got it working originally by just having the publish action as a standalone thing in a test repo. I got it working there, but not sure how to test as part of the full generation flow
> > 
> > 
> > so yeah testing of this prior to getting it merged isn't really possible (at least I haven't figured out how yet), so we just need to get it in, set it up on our own https://github.com/speakeasy-api/speakeasy-client-sdk-java repo and iterate until it works.
> 
> okay after going through some iteration myself we possibly don't need to republish the package each time we make a change as you can link to a git commit sha from workflows. I will try this out and report back on its success

nope not possible yet :( the action is currently intrinsically linked to the release tag

**Comment by TristanSpeakEasy** [comment]
> > > > @TristanSpeakEasy I'm unsure of the best way to test this. I got it working originally by just having the publish action as a standalone thing in a test repo. I got it working there, but not sure how to test as part of the full generation flow
> > > 
> > > 
> > > so yeah testing of this prior to getting it merged isn't really possible (at least I haven't figured out how yet), so we just need to get it in, set it up on our own https://github.com/speakeasy-api/speakeasy-client-sdk-java repo and iterate until it works.
> > 
> > 
> > okay after going through some iteration myself we possibly don't need to republish the package each time we make a change as you can link to a git commit sha from workflows. I will try this out and report back on its success
> 
> nope not possible yet :( the action is currently intrinsically linked to the release tag

@chase-crumbaugh I think I will just have to show you the workflow as its a bit bonkers

**Review by TristanSpeakEasy — APPROVED** [review]

**Comment by TristanSpeakEasy** [comment]
@chase-crumbaugh what is the status of this? I will have a PR today as well and it will need to bump the version number, if this is merged in first then I will use the next version number but if mine goes in first you will need to bump the version number in this again

**Comment by simplesagar** [comment]
Ok if we merge this ? Have got some customers banging down the doors for java publishing 😂

**Pull request merged**
